#
# Copyright SecureKey Technologies Inc. All Rights Reserved.
#
# SPDX-License-Identifier: Apache-2.0
#
version: '2'

services:

  orderer:
    image: hyperledger/fabric-orderer:2.2
    #在docker中的环境变量
    environment:
      - ORDERER_GENERAL_LOGLEVEL=info
      - ORDERER_GENERAL_LISTENADDRESS=0.0.0.0
      - ORDERER_GENERAL_GENESISMETHOD=file
      - ORDERER_GENERAL_GENESISFILE=/etc/hyperledger/configtx/orderer.genesis.block
      - ORDERER_GENERAL_LOCALMSPID=OrdererMSP
      - ORDERER_GENERAL_LOCALMSPDIR=/etc/hyperledger/msp/orderer
      - ORDERER_GENERAL_TLS_ENABLED=true
      - ORDERER_GENERAL_TLS_PRIVATEKEY=/etc/hyperledger/tls/orderer/server.key
      - ORDERER_GENERAL_TLS_CERTIFICATE=/etc/hyperledger/tls/orderer/server.crt
      - ORDERER_GENERAL_TLS_ROOTCAS=[/etc/hyperledger/tls/orderer/ca.crt]
      - ORDERER_GENERAL_TLS_CLIENTAUTHENABLED
      - ORDERER_GENERAL_TLS_CLIENTROOTCAS
    #comment out logging.driver in order to render the debug logs
    # logging:
    #   driver: none
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric/orderer
    command: orderer
    ports:
      - 7050:7050
    #挂载数据卷
    volumes:
      - ./artifacts:/etc/hyperledger/configtx
      - ./crypto-config/ordererOrganizations/provence.com/orderers/orderer.provence.com/msp:/etc/hyperledger/msp/orderer
      - ./crypto-config/ordererOrganizations/provence.com/orderers/orderer.provence.com/tls:/etc/hyperledger/tls/orderer
      #- ./crypto-config/peerOrganizations/yjh.provence.com/tlsca:/etc/hyperledger/tlsca
    networks:
      default:
        aliases:
          - orderer.provence.com

  YJHpeer1:
    image: hyperledger/fabric-peer:2.2
    environment:
      - CORE_VM_ENDPOINT
      - CORE_PEER_ID=peer0.yjh.provence.com
      - CORE_LOGGING_PEER=info
      # - CORE_LOGGING_GRPC=debug
      # - CORE_LOGGING_GOSSIP=debug
      # - CORE_CHAINCODE_STARTUPTIMEOUT=30s
      - CORE_CHAINCODE_LOGGING_SHIM=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=debug
      - CORE_CHAINCODE_BUILDER=${FABRIC_DOCKER_REGISTRY}${FABRIC_BUILDER_FIXTURE_IMAGE}:${FABRIC_ARCH}${FABRIC_ARCH_SEP}${FABRIC_BUILDER_FIXTURE_TAG}
      - CORE_CHAINCODE_GOLANG_RUNTIME=${FABRIC_BASE_DOCKER_REGISTRY}${FABRIC_BASEOS_FIXTURE_IMAGE}:${FABRIC_ARCH}${FABRIC_ARCH_SEP}${FABRIC_BASEOS_FIXTURE_TAG}
      - CORE_CHAINCODE_EXECUTETIMEOUT=120s
      - CORE_VM_DOCKER_ATTACHSTDOUT=false
      - CORE_PEER_LOCALMSPID=YJHMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_GOSSIP_BOOTSTRAP=127.0.0.1:7051
      - CORE_PEER_ADDRESS=peer0.yjh.provence.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.yjh.provnece.com:7051
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/tls/peer/server.key
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/tls/peer/server.crt
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/tls/peer/ca.crt
      - CORE_PEER_TLS_CLIENTAUTHREQUIRED
      - CORE_PEER_TLS_CLIENTROOTCAS_FILES
      # # the following setting starts chaincode containers on the same
      # # bridge network as the peers
      # # https://docs.docker.com/compose/networking/
      - CORE_PEER_NETWORKID=${CORE_PEER_NETWORKID}
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${CORE_PEER_NETWORKID}_default
    #comment out logging.driver in order to render the debug logs
    # logging:
    #   driver: none
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - "7051:7051"
    expose:
      - "7051"
      - "7052"
    volumes:
      - /var/run/:/var/run/
      - ./crypto-config/peerOrganizations/yjh.provence.com/peers/peer0.yjh.provence.com/msp:/etc/hyperledger/msp/peer
      - ./crypto-config/peerOrganizations/yjh.provence.com/peers/peer0.yjh.provence.com/tls:/etc/hyperledger/tls/peer
      - ./crypto-config/peerOrganizations/yjh.provence.com/tlsca:/etc/hyperledger/orgs/yjh.provence.com/tlsca
    networks:
      default:
        aliases:
          - peer0.yjh.provence.com
    depends_on:
      - orderer

  YJHpeer2:
    image: hyperledger/fabric-peer:2.2
    environment:
      - CORE_VM_ENDPOINT
      - CORE_PEER_ID=peer1.yjh.provence.com
      - CORE_LOGGING_PEER=info
      # - CORE_LOGGING_GRPC=debug
      # - CORE_LOGGING_GOSSIP=debug
      # - CORE_CHAINCODE_STARTUPTIMEOUT=30s
      - CORE_CHAINCODE_LOGGING_SHIM=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=debug
      - CORE_CHAINCODE_BUILDER=${FABRIC_DOCKER_REGISTRY}${FABRIC_BUILDER_FIXTURE_IMAGE}:${FABRIC_ARCH}${FABRIC_ARCH_SEP}${FABRIC_BUILDER_FIXTURE_TAG}
      - CORE_CHAINCODE_GOLANG_RUNTIME=${FABRIC_BASE_DOCKER_REGISTRY}${FABRIC_BASEOS_FIXTURE_IMAGE}:${FABRIC_ARCH}${FABRIC_ARCH_SEP}${FABRIC_BASEOS_FIXTURE_TAG}
      - CORE_CHAINCODE_EXECUTETIMEOUT=120s
      - CORE_VM_DOCKER_ATTACHSTDOUT=false
      - CORE_PEER_LOCALMSPID=YJHMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_ADDRESS=peer1.yjh.provence.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.yjh.provence.com:7151
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.yjh.provence.com:7051
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/tls/peer/server.key
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/tls/peer/server.crt
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/tls/peer/ca.crt
      - CORE_PEER_TLS_CLIENTAUTHREQUIRED
      - CORE_PEER_TLS_CLIENTROOTCAS_FILES
      # # the following setting starts chaincode containers on the same
      # # bridge network as the peers
      # # https://docs.docker.com/compose/networking/
      - CORE_PEER_NETWORKID=${CORE_PEER_NETWORKID}
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${CORE_PEER_NETWORKID}_default
    #comment out logging.driver in order to render the debug logs
    # logging:
    #   driver: none
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - "7151:7051"
    expose:
      - "7051"
      - "7052"
    volumes:
      - /var/run/:/var/run/
      - ./crypto-config/peerOrganizations/yjh.provence.com/peers/peer1.yjh.provence.com/msp:/etc/hyperledger/msp/peer
      - ./crypto-config/peerOrganizations/yjh.provence.com/peers/peer1.yjh.provence.com/tls:/etc/hyperledger/tls/peer
      - ./crypto-config/peerOrganizations/yjh.provence.com/tlsca:/etc/hyperledger/orgs/yjh.provence.com/tlsca
    networks:
      default:
        aliases:
          - peer1.yjh.provence.com
    depends_on:
      - orderer

  HYpeer1:
    image: hyperledger/fabric-peer:2.2
    environment:
      - CORE_VM_ENDPOINT
      - CORE_PEER_ID=peer0.hy.provence.com
      - CORE_LOGGING_PEER=info
      - CORE_CHAINCODE_LOGGING_SHIM=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=debug
      - CORE_CHAINCODE_BUILDER=${FABRIC_DOCKER_REGISTRY}${FABRIC_BUILDER_FIXTURE_IMAGE}:${FABRIC_ARCH}${FABRIC_ARCH_SEP}${FABRIC_BUILDER_FIXTURE_TAG}
      - CORE_CHAINCODE_GOLANG_RUNTIME=${FABRIC_BASE_DOCKER_REGISTRY}${FABRIC_BASEOS_FIXTURE_IMAGE}:${FABRIC_ARCH}${FABRIC_ARCH_SEP}${FABRIC_BASEOS_FIXTURE_TAG}
      - CORE_CHAINCODE_EXECUTETIMEOUT=120s
      - CORE_VM_DOCKER_ATTACHSTDOUT=false
      - CORE_PEER_LOCALMSPID=HYMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_ADDRESS=peer0.hy.provence.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer0.hy.provence.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.hy.provence.com:7051
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/tls/peer/server.key
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/tls/peer/server.crt
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/tls/peer/ca.crt
      - CORE_PEER_TLS_CLIENTAUTHREQUIRED
      - CORE_PEER_TLS_CLIENTROOTCAS_FILES
      - CORE_PEER_NETWORKID=${CORE_PEER_NETWORKID}
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${CORE_PEER_NETWORKID}_default
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - "7251:7051"
    expose:
      - "7051"
      - "7052"
    volumes:
      - /var/run/:/var/run/
      - ./crypto-config/peerOrganizations/hy.provence.com/peers/peer0.hy.provence.com/msp:/etc/hyperledger/msp/peer
      - ./crypto-config/peerOrganizations/hy.provence.com/peers/peer0.hy.provence.com/tls:/etc/hyperledger/tls/peer
      - ./crypto-config/peerOrganizations/hy.provence.com/tlsca:/etc/hyperledger/orgs/hy.provence.com/tlsca
    networks:
      default:
        aliases:
          - peer0.hy.provence.com
    depends_on:
      - orderer
  HYpeer2:
    image: hyperledger/fabric-peer:2.2
    environment:
      - CORE_VM_ENDPOINT
      - CORE_PEER_ID=peer1.hy.provence.com
      - CORE_LOGGING_PEER=info
      - CORE_CHAINCODE_LOGGING_SHIM=debug
      - CORE_CHAINCODE_LOGGING_LEVEL=debug
      - CORE_CHAINCODE_BUILDER=${FABRIC_DOCKER_REGISTRY}${FABRIC_BUILDER_FIXTURE_IMAGE}:${FABRIC_ARCH}${FABRIC_ARCH_SEP}${FABRIC_BUILDER_FIXTURE_TAG}
      - CORE_CHAINCODE_GOLANG_RUNTIME=${FABRIC_BASE_DOCKER_REGISTRY}${FABRIC_BASEOS_FIXTURE_IMAGE}:${FABRIC_ARCH}${FABRIC_ARCH_SEP}${FABRIC_BASEOS_FIXTURE_TAG}
      - CORE_CHAINCODE_EXECUTETIMEOUT=120s
      - CORE_VM_DOCKER_ATTACHSTDOUT=false
      - CORE_PEER_LOCALMSPID=HYMSP
      - CORE_PEER_MSPCONFIGPATH=/etc/hyperledger/msp/peer
      - CORE_PEER_LISTENADDRESS=0.0.0.0:7051
      - CORE_PEER_CHAINCODELISTENADDRESS=0.0.0.0:7052
      - CORE_PEER_ADDRESS=peer1.hy.provence.com:7051
      - CORE_PEER_GOSSIP_EXTERNALENDPOINT=peer1.hy.provence.com:7051
      - CORE_PEER_GOSSIP_BOOTSTRAP=peer0.hy.provence.com:7051
      - CORE_PEER_TLS_ENABLED=true
      - CORE_PEER_TLS_KEY_FILE=/etc/hyperledger/tls/peer/server.key
      - CORE_PEER_TLS_CERT_FILE=/etc/hyperledger/tls/peer/server.crt
      - CORE_PEER_TLS_ROOTCERT_FILE=/etc/hyperledger/tls/peer/ca.crt
      - CORE_PEER_TLS_CLIENTAUTHREQUIRED
      - CORE_PEER_TLS_CLIENTROOTCAS_FILES
      - CORE_PEER_NETWORKID=${CORE_PEER_NETWORKID}
      - CORE_VM_DOCKER_HOSTCONFIG_NETWORKMODE=${CORE_PEER_NETWORKID}_default
    working_dir: /opt/gopath/src/github.com/hyperledger/fabric
    command: peer node start
    ports:
      - "7351:7051"
    expose:
      - "7051"
      - "7052"
    volumes:
      - /var/run/:/var/run/
      - ./crypto-config/peerOrganizations/hy.provence.com/peers/peer1.hy.provence.com/msp:/etc/hyperledger/msp/peer
      - ./crypto-config/peerOrganizations/hy.provence.com/peers/peer1.hy.provence.com/tls:/etc/hyperledger/tls/peer
      - ./crypto-config/peerOrganizations/hy.provence.com/tlsca:/etc/hyperledger/orgs/hy.provence.com/tlsca
    networks:
      default:
        aliases:
          - peer1.hy.provence.com
    depends_on:
      - orderer

networks:
    default:
